//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerApp3 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.Motion_Sensor motion_Sensor;
        
        private Gadgeteer.Modules.GHIElectronics.Display_T35 display_T35;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        private Gadgeteer.Modules.GHIElectronics.Camera camera;
        
        private Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi_RS21;
        
        private Gadgeteer.Modules.GHIElectronics.Bluetooth bluetooth;
        
        private Gadgeteer.Modules.GHIElectronics.GasSense gasSense;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
            this.camera = new GTM.GHIElectronics.Camera(3);
            this.wifi_RS21 = new GTM.GHIElectronics.WiFi_RS21(6);
            this.bluetooth = new GTM.GHIElectronics.Bluetooth(8);
            this.gasSense = new GTM.GHIElectronics.GasSense(9);
            this.display_T35 = new GTM.GHIElectronics.Display_T35(14, 13, 12, 10);
            this.motion_Sensor = new GTM.GHIElectronics.Motion_Sensor(11);
        }
    }
}
